In [1]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.__version__)

2.10.1


In [3]:
mnist = tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train,x_test=x_train/255.0,x_test/255.0

11490434/11490434 [==============================] - 1s 0us/step


In [4]:
#budowa modelu uczenia maszynowego
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.23896956, -0.21664633, 0.03571946, 0.15906772, -0.15986456,
 -0.4300058 , 0.44659406, 0.3428196 , -0.16558 , 0.19794965]],
 dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.11731657, 0.07438542, 0.09573901, 0.10830746, 0.07873138,
 0.06009343, 0.14438747, 0.130155 , 0.07828268, 0.11260161]],
 dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1],predictions).numpy()

2.8118546

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2965 - accuracy: 0.9147
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1433 - accuracy: 0.9571
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1057 - accuracy: 0.9675
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0890 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0726 - accuracy: 0.9770


In [11]:
#ocena modelu
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0746 - accuracy: 0.9781 - 561ms/epoch - 2ms/step


[0.07455310970544815, 0.9781000018119812]

In [12]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.5550958e-08, 2.6220737e-11, 2.0181028e-06, 1.8652201e-05,
        2.3103557e-11, 1.5032312e-07, 7.1930553e-13, 9.9997044e-01,
        1.3488840e-07, 8.5538150e-06],
       [1.3842497e-06, 6.4983346e-06, 9.9990201e-01, 8.8658919e-05,
        1.2983904e-14, 3.4949315e-07, 2.1384612e-07, 8.1032085e-14,
        8.3750336e-07, 3.1667079e-14],
       [1.3471323e-06, 9.9579537e-01, 7.6117303e-04, 1.5817232e-04,
        2.9987663e-05, 6.7098277e-05, 4.2966550e-04, 2.2517287e-03,
        5.0523365e-04, 2.1953316e-07],
       [9.9935204e-01, 1.6905068e-08, 2.3435550e-05, 3.3535446e-07,
        6.4044425e-06, 5.5695779e-04, 4.3638636e-05, 1.5259435e-05,
        1.3074309e-09, 1.8966916e-06],
       [3.7950524e-06, 1.7219277e-10, 6.7077622e-07, 2.3547884e-08,
        9.9775010e-01, 4.3573236e-06, 4.4177833e-07, 9.0229078e-05,
        1.1019471e-07, 2.1503102e-03]], dtype=float32)>