In [3]:
import numpy as np

In [2]:
!pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/ad/11/52fbe97fd84c91105b651d25a122f8deed6d3519afb14f9771fac1c9b7de/numpy-1.26.3-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.2 kB 165.2 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.2 kB 187.9 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 296.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.5 MB 2.0 MB/s eta 0:00:08
    --------------------------------------- 0.3/15.5 MB 4.1 MB/s eta 0:00:04
   -- ------------------------------------- 1.0/15.5 MB 7.5 MB/s eta 0:00:02
   --- ------------------------------------ 1.5/15.5 MB 8.7 MB/s eta 0:00:02
   ------ ----------------------


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
!python.exe -m pip install --upgrade pip

  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/15/aa/3f4c7bcee2057a76562a5b33ecbd199be08cdb4443a02e26bd2c3cf6fc39/pip-23.3.2-py3-none-any.whl.metadata
  Using cached pip-23.3.2-py3-none-any.whl.metadata (3.5 kB)
Using cached pip-23.3.2-py3-none-any.whl (2.1 MB)
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1


In [5]:
wektor = np.array([5,2,6,8,4,79,4])

In [6]:
wektor

array([ 5,  2,  6,  8,  4, 79,  4])

In [7]:
print(type(wektor))

<class 'numpy.ndarray'>


In [10]:
nb = [43,6,2,478,9,58,6]

In [11]:
nb = nb + wektor

In [12]:
nb

array([ 48,   8,   8, 486,  13, 137,  10])

macierz = np.array([[1,2,3,4],[9,10,11,12],[34,56,74,37]])
macierz

In [14]:
macierz[1]

array([ 9, 10, 11, 12])

In [15]:
macierz[1][0]

9

In [17]:
macierz[1,0]

9

In [18]:
listm = [[5,2,6],[8,43,2],[8,42,2]]

In [19]:
listm[1][0]

8

In [21]:
macierz[macierz<5]

array([1, 2, 3, 4])

In [22]:
pc = (macierz>5)
macierz[pc]

array([ 9, 10, 11, 12, 34, 56, 74, 37])

In [23]:
lw = (macierz%2==0)
macierz[lw]

array([ 2,  4, 10, 12, 34, 56, 74])

In [24]:
cv = macierz[(macierz>2)&(macierz<=21)]
cv

array([ 3,  4,  9, 10, 11, 12])